
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude_types: [json]
    exclude: |
      (?x)^(.*.ambr)$

# We use the Python version instead of the original version which seems to require Docker
# https://github.com/koalaman/shellcheck-precommit
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
    - id: shellcheck
      name: shellcheck
      args: ["--severity=warning"]
      stages: [manual]

- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.33.0
  hooks:
    - id: check-github-workflows
      args: ["--verbose"]

- repo: https://github.com/codespell-project/codespell
  rev: "v2.4.1"
  hooks:
  - id: codespell
    args: ["-L", "nin"]
    stages: [manual]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.6
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/tcort/markdown-link-check
  rev: v3.13.7
  hooks:
    - id: markdown-link-check

- repo: local
  hooks:
    - id: update-locks
      name: update-locks
      entry: bash ./scripts/update-locks.sh
      language: python
      require_serial: true
      fail_fast: true
      additional_dependencies:
        - uv
