set shell := ["bash", "-c"]
set dotenv-load
set dotenv-filename := "../../.local_atlas_uri"

# Default target executed when no arguments are given.
[private]
default:
  @just --list

install:
	poetry install --with dev

[group('test')]
integration_test:
	poetry run pytest tests/integration_tests/

[group('test')]
test *args:
	poetry run pytest {{args}}

[group('test')]
test_watch filename:
	poetry run ptw --snapshot-update --now . -- -vv {{filename}}

[group('lint')]
lint:
	git ls-files -- '*.py' | xargs pre-commit run ruff --files
	git ls-files -- '*.py' | xargs pre-commit run ruff-format --files

[group('lint')]
typing:
	poetry run mypy .

[group('lint')]
codespell:
	git ls-files -- '*.py' | pre-commit run --hook-stage manual codespell --files
